# Generated by Django 3.1.5 on 2021-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210201_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tx_id', models.CharField(max_length=25)),
                ('member_username', models.CharField(max_length=50)),
                ('member_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
