# Generated by Django 3.1.5 on 2021-02-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210203_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='demo_class',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='video tutorial'),
        ),
    ]
