# Generated by Django 3.1.5 on 2021-02-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210207_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='linkedin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='whatsapp'),
        ),
    ]
