# Generated by Django 3.1.5 on 2021-01-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_auto_20210104_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpost',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tuitionpost',
            name='mobile',
            field=models.CharField(max_length=14),
        ),
    ]
