# Generated by Django 3.1.5 on 2021-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_auto_20210205_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpost',
            name='preference_tuition_style',
            field=models.CharField(choices=[('Online', 'Online'), ('Student Home', 'Student Home'), ('Coaching Center', 'Coaching Center'), ('Teacher Place', 'Teacher Place')], default='Student Home', max_length=20),
        ),
    ]
